CREATE TABLE IF NOT EXISTS friendship_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthday TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mparating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(200) NOT NULL,
    releaseDate TIMESTAMP,
    duration INTEGER,
    mparating_id INTEGER,
    CONSTRAINT fk_films_mparating
        FOREIGN KEY (mparating_id) REFERENCES mparating(id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genre_film
        FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_film_genre_genre
        FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_likes_film
        FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_likes_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendship_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_friendship_friend
        FOREIGN KEY (friend_id) REFERENCES users(id),
    CONSTRAINT fk_friendship_status
        FOREIGN KEY (status_id) REFERENCES friendship_status(id)
);